services:
  maceff-sandbox:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: maceff-sandbox:latest
    container_name: maceff-sandbox
    ports:
      - "${HOST_SSH_PORT:-2222}:22"
    environment:
      MACEFF_TZ: ${MACEFF_TZ:-America/New_York}
      CLEAN_ADMIN_HOME: "1"
      DEFAULT_PA: "maceff_user001"
      UV_LINK_MODE: "copy"
    env_file:
      - .maceff/config/global.env
      - .maceff/config/projects/${PROJ}.env
    volumes:
      - ./keys:/keys:ro
      - ./macf:/opt/macf_tools                # portable MACF framework
      - ./.maceff/framework:/opt/maceff/framework  # policies, templates, agent_defs
      - sshd_keys:/etc/ssh                    # stable host keys
      - home_all:/home                        # secure: named volume
      - shared_workspace:/shared_workspace    # secure: named volume
      - maceff_venv:/opt/maceff-venv
      # Optional mounts (e.g., Dropbox) go in docker-compose.override.yml
    restart: unless-stopped

  # Mirror named volumes to host paths (read-only snapshot on host).
  # Build the image once: docker build -t maceff-mirror:local -f docker/mirror.Dockerfile .
  # Run once: docker-compose --profile mirror up --no-deps mirror
  mirror:
    image: maceff-mirror:local
    container_name: maceff-mirror
    profiles: ["mirror"]
    command: ["/bin/sh","-lc",
      "mkdir -p /export/home /export/shared;
       chmod -R u+rwX /export/home /export/shared || true;
       rsync -rltD --delete --no-perms --no-owner --no-group /src_home/   /export/home/;
       rsync -rltD --delete --no-perms --no-owner --no-group /src_shared/ /export/shared/;
       echo '[mirror] FULL sync complete'"]
    volumes:
      - home_all:/src_home:ro
      - shared_workspace:/src_shared:ro
      - ./sandbox-home:/export/home
      - ./sandbox-shared_workspace:/export/shared

  # Mirror and keep syncing every 5 seconds while attached.
  # Run: docker-compose --profile mirror-watch up mirror-watch
  mirror-watch:
    image: maceff-mirror:local
    container_name: maceff-mirror-watch
    profiles: ["mirror-watch"]
    command: ["/bin/sh","-lc",
      "mkdir -p /export/home /export/shared;
       while :; do
         rsync -rltD --delete --no-perms --no-owner --no-group /src_home/   /export/home/;
         rsync -rltD --delete --no-perms --no-owner --no-group /src_shared/ /export/shared/;
         echo '[mirror] synced at '$(date);
         sleep 5;
       done"]
    volumes:
      - home_all:/src_home:ro
      - shared_workspace:/src_shared:ro
      - ./sandbox-home:/export/home
      - ./sandbox-shared_workspace:/export/shared

  # OPTIONAL: bind-mount home + shared directly (RW)
  # WARNING (macOS): bind mounts weaken user/ACL semantics; prefer the mirror for snapshots.
  # Use: docker-compose --profile hostbind up -d maceff-sandbox-hostbind
  maceff-sandbox-hostbind:
    extends:
      service: maceff-sandbox
    container_name: maceff-sandbox-hostbind
    profiles: ["hostbind"]            # opt-in only
    volumes:
      - ./keys:/keys:ro
      - ./tools:/opt/tools
      - ./sandbox-home:/home
      - ./sandbox-shared_workspace:/shared_workspace
      - sshd_keys:/etc/ssh
      - maceff_venv:/opt/maceff-venv

volumes:
  home_all:
  shared_workspace:
  maceff_venv:
  sshd_keys:
